name: Deployment Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint

  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'
      - name: Install dependencies
        run: npm ci
      - name: Build 
        run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: .next
          path: .next

  test:
    needs: [lint, build]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'
      - name: Install dependencies
        run: npm ci
      - uses: actions/download-artifact@v4
        with:
          name: .next
          path: .next
      - name: Run Tests
        run: npm run test
